# .gitpod.yml

tasks:
  - name: Start Docker Compose
    command: docker-compose -f docker/docker-compose.yaml up

ports:
  - port: 8081
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

# Optional: Specify the start script for your TypeScript app if you have one
# command:
#   - npm start
