services:
  reposilite:
    image: dzikoysk/reposilite:3.2.0
    ports:
      - 8081:8080
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - REPOSILITE_OPTS=--token admin:projen --shared-configuration /app/data/configuration.json
    volumes:
      - "./reposilite/configuration.json:/app/data/configuration.json"
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - '8082:4873'
    volumes:
      - "./verdaccio/htpasswd:/verdaccio/storage/htpasswd"
      - "./verdaccio/config.yaml:/verdaccio/conf/config.yaml"